import { NumberCollection } from './NumberCollection';
import { CharacterCollection } from './CharacterCollection';
import { LinkedList } from './LinkedList';
const numArray = new NumberCollection([1000, 1023, -2, 1, 0]);
const string = new CharacterCollection('xxDdfAbc');
const ll = new LinkedList();
string.sort();
ll.add(4);
ll.add(0);
ll.add(-2);
ll.add(1);
ll.sort();
